
# Basic
name:               "Superheat"



author:
  name:             Rebecca Barter

# Google-analytics
google-analytics:
  id:               ""

# Disqus
disqus:
  id:               "rlbarter"

# URL
#url:                "https://rlbarter.github.io" # the base hostname & protocol for your site
url:                "https://rlbarter.github.io" # use this url when develop
baseurl:            "superheat-examples" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
permalink:          /:title/

# Pagination
paginate:           5
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  imput:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Github"
    url:            "https://github.com/rlbarter/superheat-examples"



# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate

exclude:            [vendor]


comments: true
